"""
services/layer4/report_builder.py — Final Report Generator

Fixes Error 7 (Batch 4): This file was completely empty.
Calls Claude (via LiteLLM) to generate the human-readable FinalReport
from the Top 3 cross-domain bridges. Falls back to a structured template
when no API key is configured.
"""
import json
import os

from schemas.report import FinalReport
from schemas.layer3 import Step14Response, RankedBridge
from services.layer4.context_packager import pack_bridges_into_context


def _get_llm_client():
    """Returns LiteLLM client if ANTHROPIC_API_KEY is set, else None."""
    try:
        import litellm
        if not os.getenv("ANTHROPIC_API_KEY"):
            raise EnvironmentError("No key")
        return litellm
    except (ImportError, EnvironmentError):
        return None


async def build_report(run_id: str, step14_response: Step14Response) -> FinalReport:
    """
    Layer 4 Final Step: Generates the human-readable FinalReport.

    1. Packs the Top 3 bridges into a structured context block.
    2. Calls Claude to write the problem statement, executive summary,
       recommended experiment, and overall confidence disclaimer.
    3. Extracts contradiction warnings from bridge metadata.

    Falls back to a deterministic template if the LLM is unavailable.
    """
    bridges = step14_response.top_bridges

    if not bridges:
        return FinalReport(
            run_id=run_id,
            problem_statement="No bridges were found above the minimum score threshold.",
            top_bridges=[],
            executive_summary=(
                "The pipeline completed but found no cross-domain mechanisms that "
                "structurally match the user's bottleneck graph with sufficient confidence. "
                "Consider broadening the domain-blind query or lowering the isomorphism threshold."
            ),
            recommended_experiment="Revisit the input graph and ensure low-confidence nodes are correctly identified.",
            contradiction_warnings=[],
            confidence_disclaimer="Pipeline completed with 0 valid bridges. Confidence: N/A.",
        )

    # Build context from Top 3 bridges
    context = pack_bridges_into_context(
        bridges=bridges,
        user_query=bridges[0].match.mechanism.source_result.merged_summary[:200]
    )

    # Collect contradiction warnings (always, regardless of LLM availability)
    contradiction_warnings = []
    for bridge in bridges:
        analysis = bridge.match.mechanism.source_result.contradiction_analysis
        if analysis and analysis.conflict_detected:
            contradiction_warnings.append(
                f"Bridge '{bridge.match.mechanism.source_result.title}': "
                f"{analysis.nature_of_conflict}"
            )

    # Compute an overall confidence disclaimer
    avg_score = sum(b.scores.final_score for b in bridges) / len(bridges)
    confidence_disclaimer = (
        f"This report is based on {len(bridges)} cross-domain bridge(s) with an average "
        f"validity score of {avg_score:.2%}. "
        f"Results are generated by an AI pipeline and should be validated by domain experts "
        f"before implementation."
    )
    if contradiction_warnings:
        confidence_disclaimer += (
            f" Note: {len(contradiction_warnings)} bridge(s) contain conflicting evidence — "
            f"see contradiction warnings below."
        )

    # -----------------------------------------------------------------------
    # LLM-generated report
    # -----------------------------------------------------------------------
    client = _get_llm_client()
    if client:
        prompt = (
            "You are a cross-domain systems analyst generating a final report for an "
            "engineering team. Based on the bridges below, generate a concise report.\n\n"
            f"{context}\n\n"
            "Return a JSON object with EXACTLY these keys:\n"
            "  problem_statement: one sentence summarising the user's bottleneck problem\n"
            "  executive_summary: 3-5 sentences explaining what the top bridge means "
            "and how it solves the problem\n"
            "  recommended_experiment: one specific, measurable experiment the team "
            "should run first to validate the top bridge\n\n"
            'Output ONLY valid JSON. No explanation, no markdown fences.'
        )

        response = client.completion(
            model="claude-3-5-sonnet-20241022",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=600,
        )
        raw = response.choices[0].message.content.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        data = json.loads(raw.strip())

        return FinalReport(
            run_id=run_id,
            problem_statement=data.get("problem_statement", "See executive summary."),
            top_bridges=bridges,
            executive_summary=data.get("executive_summary", "See top bridges."),
            recommended_experiment=data.get("recommended_experiment", "See bridges."),
            contradiction_warnings=contradiction_warnings,
            confidence_disclaimer=confidence_disclaimer,
        )

    # -----------------------------------------------------------------------
    # Template fallback (no API key)
    # -----------------------------------------------------------------------
    top = bridges[0]
    top_title = top.match.mechanism.source_result.title
    top_summary = top.match.mechanism.source_result.merged_summary
    top_score = top.scores.final_score

    return FinalReport(
        run_id=run_id,
        problem_statement=(
            f"The target graph exhibits a structural bottleneck pattern that matches "
            f"the mechanism described in '{top_title}'."
        ),
        top_bridges=bridges,
        executive_summary=(
            f"The highest-ranked cross-domain bridge (score: {top_score:.2%}) was found in "
            f"'{top_title}'. Summary: {top_summary} "
            f"This mechanism has been independently validated across "
            f"{len(top.match.mechanism.source_result.sources)} source type(s), "
            f"suggesting the solution approach is transferable to the target domain."
        ),
        recommended_experiment=(
            top.match.mechanism.source_result.contradiction_analysis.recommended_experiment
            if top.match.mechanism.source_result.contradiction_analysis
            else (
                "Design a controlled A/B experiment comparing baseline behaviour "
                "against the intervention proposed by the top bridge. "
                "Measure the primary output metric under both conditions with identical inputs."
            )
        ),
        contradiction_warnings=contradiction_warnings,
        confidence_disclaimer=confidence_disclaimer,
    )
