from typing import List, Optional
from pydantic import BaseModel, Field
from .graph import CausalGraph
from .layer3 import RankedBridge


class FinalReport(BaseModel):
    """
    The structured output of Layer 4 — the complete human-readable report
    generated by Claude after analysing the Top 3 cross-domain bridges.
    """
    run_id: str
    problem_statement: str = Field(..., description="Claude's one-sentence summary of the user's bottleneck problem")
    top_bridges: List[RankedBridge]
    executive_summary: str = Field(..., description="The full plain-English explanation of the solution")
    recommended_experiment: str = Field(..., description="The single most actionable next experiment")
    contradiction_warnings: List[str] = Field(default_factory=list, description="Any unresolved contradictions flagged from Step 11.5")
    confidence_disclaimer: str = Field(..., description="Overall pipeline confidence and caveats")
